name: PR Linter

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  pr-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run PR Linter
        uses: useinsider/pr-linter@v1.13.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config: '.github/pr-linter.jsonc'
