name: PR Linter

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - assigned
      - unassigned
      - labeled
      - unlabeled

concurrency:
  group: pr-linter-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  pr-linter:
    runs-on: ["self-runner:default", team_vikings]
    permissions:
      contents: read
      issues: write
      pull-requests: write
      statuses: write
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Run PR Linter
        uses: useinsider/pr-linter@v1.13.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config: '.github/pr-linter.jsonc'
